name: internet_connection_checker_plus
description: A pure Dart package to check your internet connection with subsecond response times, even on mobile networks!
version: 2.9.1+2
homepage: https://outdatedguy.rocks
repository: https://github.com/OutdatedGuy/internet_connection_checker_plus
topics:
  - connectivity
  - internet-connection
  - offline
  - online
  - connection-checker
funding:
  - https://buymeacoffee.com/outdatedguy
  - https://github.com/sponsors/OutdatedGuy

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
